To Do list: add & remove
Krishnabot/To-Do-List pull request #2
Opened 2022-07-08 19:27 UTC by Krishnabot

- Removed all hardcoded items from the tasks array.
- Created a new JavaScript file for the new functionality.
- Implemented a function for adding a new task. 
- Implement a function for deleting a task.
- Implement a function for editing task descriptions.
- new tasks have the property completed set to false and the property index set to the value of the new array length. 
- Deleting a task updates all remaining items' indexes, so they represent the current list order and are unique. 
- All changes to the To-Do List should be saved in local storage.

2022-07-08 20:57 UTC, ahmetbozaci requested changes
# ♻️♻️♻️ STATUS: Changes Required  ♻️♻️♻️
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)

 @Krishnabot  ✋🏼 

#### Your project is excellent. You are almost done. However, there are some issues you should fix. Please fix them then your project will be approved.

___ 

### 💯  Nice to have 💯
- Your git-flow is correct. ✔️
- You set up linter files and no errors. ✔️
- Your pull request is very professional. It has a meaningful title and summary. Keep it up.✔️
- I can add and edit todo item.✔️
___


### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._

___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
___

### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._


___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-07-08 20:57 UTC, ahmetbozaci commented on src/addremove.js
> +export { getLocalStorage, addToDoTask, deleteToDoTask };
- [ ] Completed should change to `true` when clicking the checkbox. It is always false now. Kindly fix it.
![image](https://user-images.githubusercontent.com/38635158/178060994-68f82971-93b8-4a78-bf98-e264510b51b0.png)
- [ ] You gave the add event listener to the div tag. That's why ı can delete when ı click on the empty space. I have to delete item when click on the delete icon or clear completed button. Kindly fix it.

2022-07-09 09:59 UTC, vickymarz requested changes
Hi @Krishnabot , 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-09 09:59 UTC, vickymarz commented on src/addremove.js
> +};
- [ ] As the previous reviewer has earlier suggested, Kindly ensure that when a checkbox is checked, its value changes to true to indicate that the task is completed. It is easier to delete all completed todos that way.

2022-07-09 09:59 UTC, vickymarz commented on src/addremove.js
> +  localStorageTasks(Task);
- [ ] When I try to add new todos, they are not saved instantly into the local storage as shown here until i close and reopen the local storage 👇 

![image](https://user-images.githubusercontent.com/63473584/178100838-e999ab55-f9b4-4000-bccc-1bcb4b9208d0.png)
Kindly check it out.

2022-07-09 09:59 UTC, vickymarz commented on src/addremove.js
> +};
- [ ] When I delete a to-do item, the indexes are not updating. The expected behavior is for the indexes of the todos to update after an item has been deleted as specified in the requirement. Please fix it 👍

2022-07-10 02:30 UTC, youmari requested changes
Hi @Krishnabot , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ Great title and short summary
✔️ No linter error 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-10 02:30 UTC, youmari commented on src/index.js
> +});
- [ ] Nice for trying to solve the problem that the previous reviewer asked but is it still it happened when I delete a task the data in the local storage doesn't get updated  I suggest when you call the delete function  to delete a task you should immediately call the a function that update the localstorage

2022-07-10 02:30 UTC, youmari commented on src/index.js
> -    checkBox.checked = e.completed;
- [ ] Please make sure that the checkboxes are working right now they are not so like the previous reviewer asked you should make them work.

2022-07-12 10:17 UTC, muneebulrehman requested changes
Hi @Krishnabot , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-12 10:17 UTC, muneebulrehman commented on src/addremove.js
> +};
- [ ] Upon removing one item from the list and adding another item immediately after that followed by reloading, only the last item is visible and local storage also holds only this last added item. Consider fixing it. If you don't understand what I am saying, contact me on slack.

2022-07-14 16:31 UTC, omarsalem7 approved these changes
Hi @Krishnabot 😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ No linter errors. 
✅ Descriptive pull request 
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-14 16:31 UTC, merged